# Usar la imagen de SQL Server 2022
FROM mcr.microsoft.com/mssql/server:2022-latest

# Aceptar el acuerdo de licencia de usuario final y establecer la contraseña del SA
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Pas5word&

# Exponer el puerto 1433 para las conexiones
EXPOSE 1433

